name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your primary branch if different

permissions:
  contents: write  # Ensure 'write' permission for GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          allow_empty_commit: false
          keep_files: false
          force_orphan: true  # Creates an orphan gh-pages branch if it doesn't exist
          enable_jekyll: false
          exclude_assets: .github  # Exclude .github directory if present

      - name: Setup Git config (for first-time branch creation)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
